name: Nodejs
on: pull_request

jobs:
 build:
   name: Nodejs
   # This job runs on Linux
   runs-on: ubuntu-latest
   env:
     IMAGE_NAME: nodejs-example
     IMAGE_TAG: latest
   steps:
     - uses: actions/checkout@v1

     - name: Docker build
       run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

     - name: Test
       run: docker run --rm -i $IMAGE_NAME:$IMAGE_TAG yarn test